config/routes.rb
Rails.application.routes.draw do
  
  
  
  devise_for :admins
  mount Ckeditor::Engine => '/ckeditor'

  resources :applicant_responses
  get 'applicant_responses/scores'

  resources :shortlists

  devise_for :users
  resources :assessments
  resources :job_applicants
  resources :jobpostings
  
  get 'homepage/index'
  get 'homepage/hr_products'
  get 'homepage/services'
  get 'homepage/about_us'
  get 'homepage/performance'
  get 'homepage/payroll_expenses'
  get 'homepage/careers'
  get 'homepage/contact_us'
  get 'homepage/financial_perf'
  get 'homepage/our_team'
  get 'homepage/new'
  get 'homepage/jobpostings'
  get 'homepage/show'
  get 'homepage/job_apply'
  get 'homepage/support'
  get 'homepage/admin_page'
  get 'homepage/remove'

  

  
  
  
  

  match 'create',    to: 'homepage#create', via: :post

  

  root 'homepage#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable
end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question
	has_one :response
end

app/models/applicant_response.rb
class ApplicantResponse < ActiveRecord::Base
	has_many :questions
	# has_many :answers, through: :question
	belongs_to :assessment
	has_many :responses
	belongs_to :user
	accepts_nested_attributes_for :responses

	after_save :calculate_score


	def calculate_score
		# Client.where("orders_count = ? AND locked = ?", params[:orders], false)
		user_responses = Response.where("user_id = ? AND assessment_id = ?", self.user_id, self.assessment_id)
		user_answers=[]
		user_responses.each do |response|
			user_answers << response.response_text	
		end
		assessment = Assessment.find_by_id(self.assessment_id)
		questions = assessment.questions
		correct_answers = []
		questions.each do |q|
			correct_answers << q.correct_answer
		end

		puts "user answers #{user_answers}"
		puts "correct_answers #{correct_answers}"
		valid_score = nil
		compare = user_answers.zip(correct_answers).map { |x, y| x == y }
		# if compare.count(true) == compare.count
		# 	valid_score = compare.count(true)
		if compare.count(false) == compare.count
			valid_score = 0
		else
			valid_score = compare.count(true)
			puts "***********************************"
			puts "Score is #{valid_score}"
			puts "***********************************"
		end
		

		#Response.where(:user_id => self.user_id).delete_all

		testscore = TestScore.new
		testscore.user_id = self.user_id
		testscore.assessment_id = self.assessment_id
		testscore.score = valid_score
		testscore.save!
		@test_score = valid_score
		@test_type = Assessment.find_by_id(testscore.assessment_id).test_type
		puts "****test_type= #{@test_type}"
		if @test_type == "Optional"
			sendmail = send_responses_mail(testscore, @test_score)
			puts "HI I am in Optional"
		else
			puts "HI I am in Descriptive"
			sendmail = applicant_response_mail(testscore)
		end
		
		
		user = User.find_by_id(self.user_id)
		user.password = "test1234"
		user.save!
	end
	def applicant_response_mail(testscore)
		puts "testscore is #{testscore.inspect}"
			@assignment_name = Assessment.find_by_id(testscore.assessment_id).name
			@user_name = User.find_by_id(testscore.user_id).name
			@response = Response.where(:user_id=>self.user_id)
			
			#puts "response #{@response} score is #{score}"
			if UserMailer.applicant_response_mail(@assignment_name, @user_name, @response).deliver
				Response.where(:user_id => self.user_id).delete_all
			end
			true
	end

	def send_responses_mail(testscore, score)
			@assignment_name = Assessment.find_by_id(testscore.assessment_id).name
			@user_name = User.find_by_id(testscore.user_id).name
			@response = Response.where(:user_id=>testscore.user_id)
			puts "response #{@response} score is #{score}"
			@score = score
			if UserMailer.send_responses_mail(@assignment_name, @user_name, @response, @score).deliver
				Response.where(:user_id => self.user_id).delete_all
			end
			true
	end

		# def sendmail
		# 	@test_assessment_name = Assessment.find_by_id(self.assessment_id)
		# 	@test_user_name = User.find_by_id(self.user_id)
		# 	@user_name = @test_user_name.name
			
		
			
		# 	UserMailer.applicant_response_mail(@test_assessment_name, @test_user_name, @test_score).deliver_now
		# end
		
		
		
		#send mail with score and mail id of user
		

		# change password of user

		




		

end

app/models/assessment.rb
class Assessment < ActiveRecord::Base
	has_many :responses
	has_many :applicant_responses
	belongs_to :users
	has_many :questions, :dependent => :destroy
	has_many :test_scores
	accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

end

app/models/homepage.rb
class Homepage < ActiveRecord::Base
end

app/models/job_applicant.rb
class JobApplicant < ActiveRecord::Base
	mount_uploader :attachment, ResumeUploader
	validates :name, presence: true
	validates :emailid, presence: true
	validates_format_of :emailid, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
	
end

app/models/jobposting.rb
class Jobposting < ActiveRecord::Base
	validates :Job_Title, presence: true
	
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :assessment
	has_many :responses
	has_many :answers, :dependent => :destroy
	has_one :response
	accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/models/response.rb
class Response < ActiveRecord::Base
	belongs_to :user
	belongs_to :question
	belongs_to :answer
	belongs_to :assessment

	





	
end

app/models/shortlist.rb
class Shortlist < ActiveRecord::Base
	has_one :user
	


	accepts_nested_attributes_for :user
end

app/models/test_score.rb
class TestScore < ActiveRecord::Base
	belongs_to :assessment
	belongs_to :user
	
	
end

app/models/user.rb
class User < ActiveRecord::Base
	
	has_many :assessments
	belongs_to :shortlist
	has_many :responses
	has_many :test_scores
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,  :confirmable,
           :trackable, :validatable, :timeoutable



      
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

	before_filter :authenticate_admin!, only: [:admin_page]

  before_action :set_test_score, only: [:remove]
  
def index

  
  
  
end

  def jobpostings
    @jobpostings = Jobposting.all

  end





  def job_apply

    #@application = Homepage.new
  	# @jobpostings = Jobposting.all

  	if params[:title]
      @job = Jobposting.where(:Job_Title=> params[:title]).first
      puts "*************************************************"
      puts "*************************************************"
      @application = Homepage.new
    
    end
  end
  def assessments
    @assessments = Assessments.all
  end
  def shortlists
    @shortlists = Shortlist.all
  end
  def admin_page
    @test_score = TestScore.all
    @job_applicants = JobApplicant.all

  end
  def remove
  # @test_score = TestScore.find(params[:id]).first
  @test_score.destroy
  # respond_to do |format|
  flash[:notice] = "Record successfully deleted"
    redirect_to :action => 'admin_page'
  # end
end
  
  


private

def set_test_score
  @test_score = TestScore.find(params[:id])
end



  
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
 module ApplicationHelper
  
end
  

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/jobpostings_helper.rb
module JobpostingsHelper
end

app/helpers/onlinetests_helper.rb
module OnlinetestsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/shortlists_helper.rb
module ShortlistsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	
end

app/views/homepage/about_us.html.erb
<style type="text/css">
	body 
	{
		font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
	 	color: black;
	 	
	}

	
	.nav > li > a{
		
		color: #2952CC;
		text-align: left;

	}
	
	
	.linkbar {
		display: inline-block;
		width: 15%;
		text-align: left;


	}
	
	.linkbar1 {
		display: inline-block;
		width: 83%;
	}
	.linkbar2 {

		display: inline-block;
		width: 25%;
		
		
	}

	
	.nav {
		vertical-align: text-top;

	}
	




	


</style><br>


	



<div class = "linkbar">


		
		
			<ul class = "nav">
			<li><a href = <%=homepage_about_us_path%>>Company</a></li>
			<li><a href = <%=homepage_our_team_path%>>Executive Team</a></li>
			<li><a href = <%=homepage_financial_perf_path%>>Financial Performance</a></li>
			
			<li><a href = <%=homepage_contact_us_path%>>Contact Us</a></li>
			</ul></div>


		<div class = "linkbar1"><img src = "/assets/Company.png" align = "right" height = "170px" width = "220px">
		
			<font  color = "#333399" size = "5">Company</font><hr width="75%" align = "left"> 
			
			<font>
				LIBSERV is an HR software services company. We develop software products that automate business processes for companies<br>to ensure a seamless experience for today’s mobile and multi-location workforce. Our products include WorkforceTM and Performance.
				<br><br>
				We also integrate with a payroll solution called Quikchex to provide customers with a full HR management system.

 

Established in 2014, we are very much a startup at heart. We also leverage the reputation of the PSS group, a leader in recruitment and staffing services, of which we are a part. Through our sister companies, we integrate the delivery of HR software services with premier recruitment and staffing services. 
				

			</font></div>
				
				
			
			
			
			
	
	

app/views/homepage/admin_page.html.erb
<h5 align = "right"><% if admin_signed_in? %>

Hello, LIBSERV Admin. Not you?
<% end %> | <%= link_to "Logout", destroy_admin_session_path, :method => :delete %>
</h5><hr width="100%" align = "left">


<p id="notice"><%= notice %></p>
<div>

<h4><img src = "/assets/rightarrow1.gif">	
<%= link_to "New Job Post", :controller => "jobpostings", :action => "new" %> | <%= link_to "View All Job Posts", :controller => "jobpostings", :action => "index" %><hr width="100%" align = "left">
<img src = "/assets/rightarrow1.gif">
<%= link_to "New Assessment", :controller => "assessments", :action => "new" %> |
<%= link_to "View All Assessments", :controller => "assessments", :action => "index" %><hr width="100%" align = "left">
<img src = "/assets/rightarrow1.gif">
<%= link_to "Shortlist Candidate", :controller => "shortlists", :action => "new" %></h4></div>
<hr width="100%" align = "left">

<h3><img src = "/assets/rightarrow1.gif"> Listing Job Applicants</h3>

<table class="table table-hover">
  
    <tr>
      <td align = "center"><h4>Name</h4></td>
      <td align = "center"><h4>E-Mail ID</h4></td>
      <td align = "center"><h4>Contact</h4></td>
      <td align = "center"><h4>Applied For</h4></td>
      <td align = "center"><h4>CV Attached</h4></td>
      <td colspan="3" align = "center"><h4>Actions</h4></td></th>
    </tr>
  

  
    <% @job_applicants.each do |job_applicant| %>
      <tr>
        <td align = "center"><font color = "#333399"><%= job_applicant.name %></td>
        <td align = "center"><font color = "#333399"><%= job_applicant.emailid %></td>
        <td align = "center"><font color = "#333399"><%= job_applicant.contact_no %></td>
        <td align = "center"><font color = "#333399"><%= job_applicant.applying_for %></td>
        <td align = "center"><a href =<%= job_applicant.attachment %>>Resume</a></td>
        <td align = "center"><%= link_to 'Show', job_applicant %></td>
        <td align = "center"><%= link_to 'Edit', edit_job_applicant_path(job_applicant) %></td>
        <td align = "center"><%= link_to 'Shortlist', :controller=>"shortlists", :action=>"new" %>
        <%#= link_to 'Destroy', job_applicant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr></font>
    <% end %>
  
</table>
<div>
<h3><img src = "/assets/rightarrow1.gif"> Listing Candidate's Scores</h3>
<table class="table table-hover">

					
					
						<tr>

							<td align = "center"><h4>Candidate Name&nbsp;</h4></td>
							<td align = "center"><h4>Assessment Name&nbsp;</h4></td>

							<td align = "center"><h4>Score&nbsp;</h4></td>
							<td align = "center"><h4>Submitted On</h4></td>
							<td align = "center"><h4>Action</h4></td>
							
						</tr>
							
						<% @test_score.each do |ts| %>	

						<tr>


						<h5>
								<td align = "center"><font color = "#333399"><%= ts.user.name %></td>
								<td align = "center"><font color = "#333399"><%= ts.assessment.name %></td>
								<td align = "center"><font color = "#333399"><%= ts.score %></td>
								
								<td align = "center"><font color = "#333399"><%= ts.created_at.strftime("%d-%m-%Y") %></td>
								<td align = "center"><%= link_to 'Delete', :controller=>"homepage", :action=>"remove", :id=>ts %></td>
								
								
							</h5>
						</tr>
						<% end %>
					</table>
</div> 

<h4></h4><br>

app/views/homepage/contact_us.html.erb
<script src="https://maps.googleapis.com/maps/api/js"></script>

<style type="text/css">
	body 
	{
		font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
	 	color: black;
	 	
	}

	
	.nav > li > a{
		
		color: #2952CC;
		text-align: left;

	}
	
	
	.linkbar {
		display: inline-block;
		width: 15%;
		text-align: left;


	}
	
	.linkbar1 {
		display: inline-block;
		width: 83%;
	}
	.linkbar2 {

		display: inline-block;
		width: 25%;
		
		
	}

	
	.nav {
		vertical-align: text-top;

	}
	




	


</style><br>

<div class = "linkbar">



		
		
			<ul class = "nav">
			<li><a href = <%=homepage_about_us_path%>>Company</a></li>
			<li><a href = <%=homepage_our_team_path%>>Executive Team</a></li>
			<li><a href = <%=homepage_financial_perf_path%>>Financial Performance</a></li>
			
			<li><a href = <%=homepage_contact_us_path%>>Contact Us</a></li>
			</ul></div>
			<div class = "linkbar1">
			<img src = "/assets/noimage.gif" align = "right" height = "170px" width = "220px">


			<font  color = "#333399" size = "5">Contact Us</font><hr width="75%" align = "left">
			
			<font>
				If you would like to become a future client, partner or employee of ours,<br>we would like to hear from you.<hr width = "75%" align = "left">
				<font size = "5" color = "#333399">Address:</font><br>
				308 Prabhadevi Estate <br>
				V.S. Marg<br>
				Prabhadevi <br>
				Mumbai 400025 <br><br>
				<font  color = "#333399">Mail Us :&nbsp;<a href = "mailto:info@libserv.co">info@libserv.co</a></font><br>
				<font   color = "#333399">Call Us :&nbsp;<a href = "tel:+912266697061">+912266697061</a>&nbsp;<a href = "tel:+919833475662">+919833475662</a>
				</font>
			</font></div> 
		
		
	
	







<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script><style>#gmap_canvas img{max-width:none!important;background:none!important}</style><script type="text/javascript"> function init_map(){var myOptions = {zoom:14,center:new google.maps.LatLng(19.0158466,72.82799729999999),mapTypeId: google.maps.MapTypeId.ROADMAP};map = new google.maps.Map(document.getElementById("gmap_canvas"), myOptions);marker = new google.maps.Marker({map: map,position: new google.maps.LatLng(19.0158466, 72.82799729999999)});infowindow = new google.maps.InfoWindow({content:"<b>LIBSERV India Pvt. Ltd.</b><br/>308, Prabhadevi Estate<br/>V.S Marg<br/>Prabhadevi<br/>400025, Mumbai" });google.maps.event.addListener(marker, "click", function(){infowindow.open(map,marker);});infowindow.open(map,marker);}google.maps.event.addDomListener(window, 'load', init_map);</script>
</body>
</html>

app/views/homepage/financial_perf.html.erb
<style type="text/css">
	body 
	{
		font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
	 	color: black;
	 	
	}

	
	.nav > li > a{
		
		color: #2952CC;
		text-align: left;

	}
	
	
	.linkbar {
		display: inline-block;
		width: 15%;
		text-align: left;


	}
	
	.linkbar1 {
		display: inline-block;
		width: 83%;
	}
	.linkbar2 {

		display: inline-block;
		width: 25%;
		
		
	}

	
	.nav {
		vertical-align: text-top;

	}
	




	


</style><br>
<div class = "linkbar">



		
		
			<ul class = "nav">
			<li><a href = <%=homepage_about_us_path%>>Company</a></li>
			<li><a href = <%=homepage_our_team_path%>>Executive Team</a></li>
			<li><a href = <%=homepage_financial_perf_path%>>Financial Performance</a></li>
			
			<li><a href = <%=homepage_contact_us_path%>>Contact Us</a></li>
			</ul></div>


		<div class = "linkbar1">
		<img src = "/assets/noimage.gif" align = "right" height = "170px" width = "200px">
		
			<font  color = "#333399" size = "5">Financial Performance</font><hr width="75%" align = "left"> 
			
			<font>
				
				<br>

			</font></div>
			
			
	
	

app/views/homepage/our_team.html.erb
<script type="text/javascript">
$('#myModal').on('shown.bs.modal', function () {
  $('#myInput').focus()
})
$('#myModal1').on('shown.bs.modal', function () {
  $('#myInput').focus()
})
$('#myModal2').on('shown.bs.modal', function () {
  $('#myInput').focus()
})
$('#myModal3').on('shown.bs.modal', function () {
  $('#myInput').focus()
})
$('#myModal4').on('shown.bs.modal', function () {
  $('#myInput').focus()
})
</script>
<style type="text/css">
	body 
	{
		font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
	 	color: black;
	 	
	}

	
	.nav > li > a{
		
		color: #2952CC;
		text-align: left;

	}
	
	
	.linkbar {
		display: inline-block;
		width: 15%;
		text-align: left;


	}
	
	.linkbar1 {
		display: inline-block;
		width: 83%;
	}
	.linkbar2 {

		display: inline-block;
		width: 25%;
		
		
	}

	
	.nav {
		vertical-align: text-top;

	}
	




	


</style><br>
<div class = "linkbar">



		
		
			<ul class = "nav">
			<li><a href = <%=homepage_about_us_path%>>Company</a></li>
			<li><a href = <%=homepage_our_team_path%>>Executive Team</a></li>
			<li><a href = <%=homepage_financial_perf_path%>>Financial Performance</a></li>
			
			<li><a href = <%=homepage_contact_us_path%>>Contact Us</a></li>
			</ul></div>


		<div class = "linkbar1">
		<img src = "/assets/noimage.gif" align = "right" height = "150px" width = "220px">
		
			<font  color = "#333399" size = "5">Meet The Team</font><hr width="69%" align = "left"> 
			
			<font>
				Our executive team is a combination of business managers and technology addicts.Their work is supported by a seasoned<br>team of advisors from the HR industry, product technology field and management consulting domain. We work together to<br>develop products and deliver services that will change how businesses do HR. 
				<br><hr width="68%" align = "left"><font color = "#333399" size = "3">Board Of Advisors</font><hr width="68%" align = "left">

			</font>
			<table width = "68%">
				<tr>
					<td width = "25%" align = "left"><img src = "/assets/Andre-Lobo.jpg" height = "150" width = "145"></td>
					<td width = "25%" align = "center"><img src = "/assets/mario.jpg" height = "150"></td>
					<td width = "25%" align = "right"><img src = "/assets/Arun-Shenoy.jpg" height = "150"></td>

				</tr>
				<tr>
					<td width = "25%" align = "left"><b>Andre Lobo<br>Chief Executive Officer</b></td>
					<td width = "25%" align = "center"><b>Mario Lobo<br>Executive Director</b></td>
					<td width = "25%" align = "right"><b>Arun Shenoy<br>Head Payroll</b></td>
				</tr>
				<tr>
					<td width = "25%" align = "left"><a href = "" data-toggle="modal" data-target="#myModal">Read More</a></td>
					<td width = "25%" align = "center"><a href = "" data-toggle="modal" data-target="#myModal1">Read More</a></td>
					<td width = "25%" align = "right"><a href = "" data-toggle="modal" data-target="#myModal2">Read More</a></td>
				</tr>
			</table>
			<hr width="68%" align = "left"><font color = "#333399" size = "3">Technology Team</font><hr width="68%" align = "left">

			</font>
			<table width = "68%">
				<tr>
					<td width = "25%" align = "left"><img src = "/assets/noimage.gif" height = "150" width = "145"></td>
					<td width = "25%" align = "center"><img src = "/assets/noimage.gif" height = "150"></td>
					<td width = "25%" align = "right"><img src = "/assets/noimage.gif" height = "150"></td>

				</tr>
				<tr>
					<td width = "25%" align = "left"><b>Anurag Jaiswal<br>Product Manager & Developer</b></td>
					<td width = "25%" align = "center"><b>Prashant Pola | Developer</b></td>
					<td width = "25%" align = "right"><b>Harshvardhan | Developer</b></td>
				</tr>
				<tr>
					<td width = "25%" align = "left"><a href = "" data-toggle="modal" data-target="#myModal3">Read More</a></td>
					<td width = "25%" align = "center"><a href = "">Read More</a></td>
					<td width = "25%" align = "right"><a href = "">Read More</a></td>
				</tr>
			</table>
			<hr width="68%" align = "left"><font color = "#333399" size = "3">Support Team</font><hr width="68%" align = "left">

			</font>
			<table width = "68%">
				<tr>
					<td width = "25%" align = "left"><img src = "/assets/noimage.gif" height = "150" width = "145"></td>
					<td width = "25%" align = "center"><img src = "/assets/noimage.gif" height = "150"></td>
					<td width = "25%" align = "right"><img src = "/assets/noimage.gif"height = "150"></td>

				</tr>
				<tr>
					<td width = "25%" align = "left"><b>Soujanya Nanthur<br>Process Associate</b></td>
					<td width = "25%" align = "center"><b>ABC | ABC</b></td>
					<td width = "25%" align = "right"><b>ABC | ABC</b></td>
				</tr>
				<tr>
					<td width = "25%" align = "left"><a href = "" data-toggle="modal" data-target="#myModal4">Read More</a></td>
					<td width = "25%" align = "center"><a href = "">Read More</a></td>
					<td width = "25%" align = "right"><a href = "">Read More</a></td>
				</tr>
			</table>
<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Andre Lobo</h4>
      </div>
      <div class="modal-body">
        Andre Lobo is spearheading the operations of Libserv. He has established the company’s multi-client data processing center and forged strategic partnerships with select vendors to integrate the delivery of HR BPO services for client organizations.<br><br>

Prior to joining Libserv as its CEO, Andre has worked in the financial services industry for reputed multinational organizations like Standard Chartered Bank and the Aditya Birla Group. He completed his MBA from IESE Business School, Barcelona Spain. He is also an alumnus of the University of Michigan, Ann Arbor and London Business School.
      </div>
      
    </div>
  </div>
</div>
<div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Mario Lobo</h4>
      </div>
      <div class="modal-body">
        Mario is one of the pioneers in Executive Search in India, having spent over 31 years in the industry. With extensive experience in developing and Managing Strategic Relationships, he has helped clients in identifying the roadblocks related to resources and skills and assisted various client organizations with critical strategic inputs during restructuring, salary benchmarking and in different organizational development initiatives. <br><br>

Mario takes a lot of interest in analyzing new organization structures and proposing change management across several industry sectors. His work has been featured in major national publications. He is on the board of a large number of prestigious Management Business Schools in India and is a Speaker at leading academic and business forums. <br><br>

Mario holds a degree in Arts from the University College of Arts in Jaipur and an MBA from the Xavier Labour Relations Institute, Jamshedpur (affiliated with Loyola University, USA).
      </div>
      
    </div>
  </div>
</div>
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Arun Shenoy</h4>
      </div>
      <div class="modal-body">
        Arun joined Lobo Staffing Solutions (LSS) in 2004. Over the years he has held several key positions in LSS including Regional Manager, Head HR , Zonal Head and National Head - BD & CRM . As a member of the core team, he was responsible for converting LSS from a Contract Staffing Company to an national comprehensive HR Solutions Company. <br><br>

He has over 28 years experience in HR, operations, client relations, business development and compliances. Prior to joining LSS, he worked with Unit Trust of India. Arun holds a Bachelor’s degree in Science, with a Post Graduate Diploma in Management Studies and MBA in HR. He is a Certified Associate of Indian Institute of Bankers (UTI).
      </div>
      
    </div>
  </div>
</div>
<div class="modal fade" id="myModal3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Anurag Jaiswal</h4>
      </div>
      <div class="modal-body">
        Brings 3 years of experience to LIBSERV in design, technical implementation and technical support for HRMS products for SME and enterprise companies. He has a Bachelor and Master degree in Computer Applications. 
      </div>
      
    </div>
  </div>
</div>
<div class="modal fade" id="myModal4" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Soujanya Nanthur</h4>
      </div>
      <div class="modal-body">
        Has over 6 years of experience in HR administration and support for TSR Darashaw. Soujanya oversees all support related issues for LIBERV’s clients and is involved in all first time implementations and delivery of ongoing customer support. She is a B.Com and M.Com from Mumbai University. 
      </div>
      
    </div>
  </div>
</div>
			</div>
			
			
	
	