config/routes.rb
Rails.application.routes.draw do
  
  
  
  devise_for :admins
  mount Ckeditor::Engine => '/ckeditor'

  resources :applicant_responses
  get 'applicant_responses/scores'

  resources :shortlists

  devise_for :users
  resources :assessments
  resources :job_applicants
  resources :jobpostings
  
  get 'homepage/index'
  get 'homepage/hr_products'
  get 'homepage/services'
  get 'homepage/about_us'
  get 'homepage/performance'
  get 'homepage/payroll_expenses'
  get 'homepage/careers'
  get 'homepage/contact_us'
  get 'homepage/financial_perf'
  get 'homepage/our_team'
  get 'homepage/new'
  get 'homepage/jobpostings'
  get 'homepage/show'
  get 'homepage/job_apply'
  get 'homepage/support'
  get 'homepage/admin_page'
  get 'homepage/remove'

  

  
  
  
  

  match 'create',    to: 'homepage#create', via: :post

  

  root 'homepage#index'

end

app/models/job_applicant.rb
class JobApplicant < ActiveRecord::Base
	mount_uploader :attachment, ResumeUploader
	validates :name, presence: true
	validates :emailid, presence: true
	validates_format_of :emailid, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
	
end

app/controllers/job_applicants_controller.rb
class JobApplicantsController < ApplicationController
  before_action :set_job_applicant, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_admin!, only: [:index]
  # GET /job_applicants
  # GET /job_applicants.json
  def index
    @job_applicants = JobApplicant.all
  end

  # GET /job_applicants/1
  # GET /job_applicants/1.json
  def show
  end

  # GET /job_applicants/new
  def new
    if params[:title]
      @job = Jobposting.where(:Job_Title=> params[:title]).first
    
      
    end
    @job_applicant = JobApplicant.new
  

  end

  # GET /job_applicants/1/edit
  def edit
  end

  # POST /job_applicants
  # POST /job_applicants.json
  def create
    @job_applicant = JobApplicant.new(job_applicant_params)


    respond_to do |format|
      if @job_applicant.save
        UserMailer.apply_confirmation(@job_applicant).deliver
        UserMailer.job_application(@job_applicant).deliver
        
        format.html { redirect_to @job_applicant, notice: 'Job applicant was successfully created.' }
        format.json { render :show, status: :created, location: @job_applicant }
      else
        
        format.html { render :new }
        format.json { render json: @job_applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_applicants/1
  # PATCH/PUT /job_applicants/1.json
  def update
    respond_to do |format|
      if @job_applicant.update(job_applicant_params)
        format.html { redirect_to @job_applicant, notice: 'Job applicant was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_applicant }
      else
        format.html { render :edit }
        format.json { render json: @job_applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_applicants/1
  # DELETE /job_applicants/1.json
  def destroy
    @job_applicant.destroy
    respond_to do |format|
      format.html { redirect_to job_applicants_url, notice: 'Job applicant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_applicant
      @job_applicant = JobApplicant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_applicant_params
      params.require(:job_applicant).permit(:name, :emailid, :contact_no, :applying_for, :attachment)
    end
end

app/helpers/job_applicants_helper.rb
module JobApplicantsHelper
end

app/views/job_applicants/edit.html.erb
<h1>Editing Job Applicant</h1>

<%= render 'form' %>

<%= link_to 'Show', @job_applicant %> |
<%= link_to 'Back', job_applicants_path %>

app/views/job_applicants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Job Applicants</h1>

<table class="table table-bordered table-stripped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Emailid</th>
      <th>Contact no</th>
      <th>Applying for</th>
      <th>Attachment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @job_applicants.each do |job_applicant| %>
      <tr>
        <td><%= job_applicant.name %></td>
        <td><%= job_applicant.emailid %></td>
        <td><%= job_applicant.contact_no %></td>
        <td><%= job_applicant.applying_for %></td>
        <td><%= job_applicant.attachment %></td>
        <td><%= link_to 'Show', job_applicant %></td>
        <td><%= link_to 'Edit', edit_job_applicant_path(job_applicant) %></td>
        <td><%= link_to 'Destroy', job_applicant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job applicant', new_job_applicant_path %> | <%= link_to "Logout", destroy_admin_session_path, :method => :delete %>

app/views/job_applicants/new.html.erb
 <style type="text/css">
  body 
  {
    font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    color: black;
    
  }

  
  .nav > li > a{
    
    color: #2952CC;
    text-align: left;

  }
  
  
  .linkbar {
    display: inline-block;
    width: 15%;
    text-align: left;


  }
  
  .linkbar1 {
    display: inline-block;
    width: 83%;
  }
  .linkbar2 {

    display: inline-block;
    width: 25%;
    
    
  }

  
  .nav {
    vertical-align: text-top;

  }
  




  


</style><br>
<div class = "linkbar">



    
    
      <ul class = "nav">
      
      <li><a href = <%=homepage_jobpostings_path %>>Job Openings</a></li>
      
      </ul></div>


    <div class = "linkbar1">
    <img src = "/assets/jobapply.png" align = "right" height = "150px" width = "170px">
    
      <font  color = "#333399" size = "5">Apply For The Job</font><hr width="80%" align = "left">
<%= form_for @job_applicant, html: { multipart: true } do |f| %>
  <% if @job_applicant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job_applicant.errors.count, "error") %> prohibited this job_applicant from being saved:</h2>

      <ul>
      <% @job_applicant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Your Name :" %><br>
    <%= f.text_field :name, :size=>"50", :maxlength=>"50" , :placeholder => "Enter Full Name"%>
  </div>
  <div class="field">
    <%= f.label :Email_Id, "E-Mail ID :" %><br>
    <%= f.text_field :emailid, :size=>"50", :maxlength=>"50", :placeholder => "Enter Valid Email ID"%>
  </div>
  <div class="field">
    <%= f.label :Contact_No, "Mobile Number :" %><br>
    <%= f.text_field :contact_no, :size=>"50", :maxlength=>"10", :placeholder => "10 Digit Mobile Number" %>
  </div>
  <div class="field">
    <%= f.label :applying_for, "Applying For Position :" %><%#= @job.Job_Title %><br>
    <%= f.text_field :applying_for, :value=>"#{@job.Job_Title}",  :size => "50" %>
    
  </div>
  <div class="field">
    <%= f.label :attachment, "Attach CV / Resume : (.doc, .docx, .pdf only)" %><br>
    <%= f.file_field :attachment %>
  </div>
  
  <div class="actions">
    <%= f.submit 'Apply' %>
  </div>
<% end %>

</div>

app/views/job_applicants/show.html.erb
<style type="text/css">
  body 
  {
    font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    color: black;
    
  }

  
  .nav > li > a{
    
    color: #2952CC;
    text-align: left;

  }
  
  
  .linkbar {
    display: inline-block;
    width: 15%;
    text-align: left;


  }
  
  .linkbar1 {
    display: inline-block;
    width: 83%;
  }
  .linkbar2 {

    display: inline-block;
    width: 25%;
    
    
  }

  
  .nav {
    vertical-align: text-top;

  }
  




  


</style><br>
<div class = "linkbar">



    
    
      <ul class = "nav">
      
      <li><a href = <%=homepage_jobpostings_path %>>Job Openings</a></li>
      
      </ul></div>


    <div class = "linkbar1">
    <img src = "/assets/Careers-logo.png" align = "right" height = "250px" width = "300px">
    
      <div class="alert alert-info" role="alert">Thank You For Your Application!</div><hr width="80%" align = "left">
      <font>
      <p>We will get back to you soon as your CV gets shortlisted.</p></font></div>
      <%#= form_for :homepages do |f| %>


         
   

<!--<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_job_applicant_path(@job_applicant) %> |
<%= link_to 'Back', job_applicants_path %>-->