config/routes.rb
Rails.application.routes.draw do
  
  
  
  devise_for :admins
  mount Ckeditor::Engine => '/ckeditor'

  resources :applicant_responses
  get 'applicant_responses/scores'

  resources :shortlists

  devise_for :users
  resources :assessments
  resources :job_applicants
  resources :jobpostings
  
  get 'homepage/index'
  get 'homepage/hr_products'
  get 'homepage/services'
  get 'homepage/about_us'
  get 'homepage/performance'
  get 'homepage/payroll_expenses'
  get 'homepage/careers'
  get 'homepage/contact_us'
  get 'homepage/financial_perf'
  get 'homepage/our_team'
  get 'homepage/new'
  get 'homepage/jobpostings'
  get 'homepage/show'
  get 'homepage/job_apply'
  get 'homepage/support'
  get 'homepage/admin_page'
  get 'homepage/remove'

  

  
  
  
  

  match 'create',    to: 'homepage#create', via: :post

  

  root 'homepage#index'

end

app/models/jobposting.rb
class Jobposting < ActiveRecord::Base
	validates :Job_Title, presence: true
	
end

app/controllers/jobpostings_controller.rb
class JobpostingsController < ApplicationController
  before_action :set_jobposting, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_admin!, only: [:new, :index]
  # GET /jobpostings
  # GET /jobpostings.json
  def index
    @jobpostings = Jobposting.all
  end

  # GET /jobpostings/1
  # GET /jobpostings/1.json
  def show
  end

  # GET /jobpostings/new
  def new
    @jobposting = Jobposting.new
  end

  # GET /jobpostings/1/edit
  def edit
  end

  # POST /jobpostings
  # POST /jobpostings.json
  def create
    @jobposting = Jobposting.new(jobposting_params)

    respond_to do |format|
      if @jobposting.save
        format.html { redirect_to @jobposting, notice: 'Jobposting was successfully created.' }
        format.json { render :show, status: :created, location: @jobposting }
      else
        format.html { render :new }
        format.json { render json: @jobposting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobpostings/1
  # PATCH/PUT /jobpostings/1.json
  def update
    respond_to do |format|
      if @jobposting.update(jobposting_params)
        format.html { redirect_to @jobposting, notice: 'Jobposting was successfully updated.' }
        format.json { render :show, status: :ok, location: @jobposting }
      else
        format.html { render :edit }
        format.json { render json: @jobposting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobpostings/1
  # DELETE /jobpostings/1.json
  def destroy
    @jobposting.destroy
    respond_to do |format|
      format.html { redirect_to jobpostings_url, notice: 'Jobposting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jobposting
      @jobposting = Jobposting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jobposting_params
      params.require(:jobposting).permit(:S_No, :Posted_On, :Job_Title, :CTC, :Job_Description, :Experience_Req)
    end
end

app/helpers/jobpostings_helper.rb
module JobpostingsHelper
end

app/views/jobpostings/_form.html.erb
<%= form_for(@jobposting) do |f| %>
  <% if @jobposting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jobposting.errors.count, "error") %> prohibited this jobposting from being saved:</h2>

      <ul>
      <% @jobposting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
    <%= f.label :S_No %><br>
    <%= f.text_field :S_No %>
  </div>
  <div class="field">
    <%= f.label :Posted_On %><br>
    <%= f.date_select :Posted_On %>
  </div>
  <div class="field">
    <%= f.label :Job_Title %><br>
    <%= f.text_field :Job_Title %>
  </div>
  <div class="field">
    <%= f.label :CTC %><br>
    <%= f.text_field :CTC %>
  </div>
  <div class="field">
    <%= f.label :Job_Description %><br>
    <%= f.cktext_area :Job_Description %>
  </div>
  <div class="field">
    <%= f.label :Req_Experience %><br>
    <%= f.cktext_area :Experience_Req %>
  </div>

  <div class="actions">
    <%= f.submit "Post Job" %>
  </div>
<% end %>
<%= link_to "Logout", destroy_admin_session_path, :method => :delete %> | <%= link_to "Back", :controller=>"homepage", :action=>"admin_page" %> |

app/views/jobpostings/edit.html.erb
<h1>Editing Jobposting</h1>

<%= render 'form' %>

<%= link_to 'Show', @jobposting %> |
<%= link_to 'Back', jobpostings_path %>

app/views/jobpostings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Jobpostings</h1>

<table class="table table-bordered table-stripped">
  <thead>
    <tr>
      <th>Sr.No</th>
      <th>Posted On</th>
      <th>Job Title</th>
      <th>CTC</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <% @jobpostings.each do |jobposting| %>
      <tr class "malign">
        <td><%= jobposting.S_No %></td>
        <td><%= jobposting.Posted_On %></td>
        <td><%= jobposting.Job_Title %></td>
        <td><%= jobposting.CTC %></td>

       
        <%# jobposting.Experience_Req %>
        <td><%= link_to 'View',  jobposting, :target => "_blank" %></td>
         
        <%# link_to 'Destroy', jobposting, method: :delete, data: { confirm: 'Are you sure?' } %>

          <%# jobpostings.Job_Description %>
        <td><%= link_to 'Apply', :controller=>"homepage", :action=>"careers", :title=> jobposting.Job_Title %></td>
        <%# link_to 'Destroy', jobposting, method: :delete, data: { confirm: 'Are you sure?' } %>
      </tr>
    
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jobposting', new_jobposting_path %> | <%= link_to "Logout", destroy_admin_session_path, :method => :delete %> | <%= link_to "Admin Page", :controller=>"homepage", :action=>"admin_page" %>

app/views/jobpostings/new.html.erb
<h1>New Jobposting</h1>

<%= render 'form' %>

<%= link_to 'All Job Posts', jobpostings_path %>

app/views/jobpostings/show.html.erb
<html>
<head>
  <title></title>
<script type="text/javascript">
function CloseWindow() {
        ww = window.open(window.location, "_self");
        ww.close();
    } 
</script>
<style type="text/css">
.details {
  {
    font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    color: black;
    font-size: 30pt;
}
table > tr >td {
  text-align: center;

}

</style>
</head>
<body>
  <div></div>
  <div class = "details">Details Of The Job :</div>

  <br><br>
<p id="notice"><%= notice %></p>
<table width = "100%">
  <tr>
    <td>Job ID</td>
    <td><%= @jobposting.S_No %></td>
  </tr>
    <td>Posted On</td>
    <td><%= @jobposting.Posted_On %></td>
  </tr>
    <td>Job Title</td>
    <td><%= @jobposting.Job_Title %></td>
  </tr>
    <td>Annual CTC</td>
    <td><%= @jobposting.CTC %></td>
  </tr>
    <td>Job Description</td>
    <td><%= @jobposting.Job_Description.html_safe %></td>
  </tr>
    <td>Required Experience</td>
    <td><%= @jobposting.Experience_Req.html_safe %></td>
  </tr>
</table><br><br>
  <button type="button" onclick="CloseWindow();">Close</button>

<%# link_to 'Edit', edit_jobposting_path(@jobposting) %>
<%# link_to 'Back', jobpostings_path %>
</body>
</html>