config/routes.rb
Rails.application.routes.draw do
  
  
  
  devise_for :admins
  mount Ckeditor::Engine => '/ckeditor'

  resources :applicant_responses
  get 'applicant_responses/scores'

  resources :shortlists

  devise_for :users
  resources :assessments
  resources :job_applicants
  resources :jobpostings
  
  get 'homepage/index'
  get 'homepage/hr_products'
  get 'homepage/services'
  get 'homepage/about_us'
  get 'homepage/performance'
  get 'homepage/payroll_expenses'
  get 'homepage/careers'
  get 'homepage/contact_us'
  get 'homepage/financial_perf'
  get 'homepage/our_team'
  get 'homepage/new'
  get 'homepage/jobpostings'
  get 'homepage/show'
  get 'homepage/job_apply'
  get 'homepage/support'
  get 'homepage/admin_page'
  get 'homepage/remove'

  

  
  
  
  

  match 'create',    to: 'homepage#create', via: :post

  

  root 'homepage#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable
end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question
	has_one :response
end

app/models/applicant_response.rb
class ApplicantResponse < ActiveRecord::Base
	has_many :questions
	# has_many :answers, through: :question
	belongs_to :assessment
	has_many :responses
	belongs_to :user
	accepts_nested_attributes_for :responses

	after_save :calculate_score


	def calculate_score
		# Client.where("orders_count = ? AND locked = ?", params[:orders], false)
		user_responses = Response.where("user_id = ? AND assessment_id = ?", self.user_id, self.assessment_id)
		user_answers=[]
		user_responses.each do |response|
			user_answers << response.response_text	
		end
		assessment = Assessment.find_by_id(self.assessment_id)
		questions = assessment.questions
		correct_answers = []
		questions.each do |q|
			correct_answers << q.correct_answer
		end

		puts "user answers #{user_answers}"
		puts "correct_answers #{correct_answers}"
		valid_score = nil
		compare = user_answers.zip(correct_answers).map { |x, y| x == y }
		# if compare.count(true) == compare.count
		# 	valid_score = compare.count(true)
		if compare.count(false) == compare.count
			valid_score = 0
		else
			valid_score = compare.count(true)
			puts "***********************************"
			puts "Score is #{valid_score}"
			puts "***********************************"
		end
		

		#Response.where(:user_id => self.user_id).delete_all

		testscore = TestScore.new
		testscore.user_id = self.user_id
		testscore.assessment_id = self.assessment_id
		testscore.score = valid_score
		testscore.save!
		@test_score = valid_score
		@test_type = Assessment.find_by_id(testscore.assessment_id).test_type
		puts "****test_type= #{@test_type}"
		if @test_type == "Optional"
			sendmail = send_responses_mail(testscore, @test_score)
			puts "HI I am in Optional"
		else
			puts "HI I am in Descriptive"
			sendmail = applicant_response_mail(testscore)
		end
		
		
		user = User.find_by_id(self.user_id)
		user.password = "test1234"
		user.save!
	end
	def applicant_response_mail(testscore)
		puts "testscore is #{testscore.inspect}"
			@assignment_name = Assessment.find_by_id(testscore.assessment_id).name
			@user_name = User.find_by_id(testscore.user_id).name
			@response = Response.where(:user_id=>self.user_id)
			
			#puts "response #{@response} score is #{score}"
			if UserMailer.applicant_response_mail(@assignment_name, @user_name, @response).deliver
				Response.where(:user_id => self.user_id).delete_all
			end
			true
	end

	def send_responses_mail(testscore, score)
			@assignment_name = Assessment.find_by_id(testscore.assessment_id).name
			@user_name = User.find_by_id(testscore.user_id).name
			@response = Response.where(:user_id=>testscore.user_id)
			puts "response #{@response} score is #{score}"
			@score = score
			if UserMailer.send_responses_mail(@assignment_name, @user_name, @response, @score).deliver
				Response.where(:user_id => self.user_id).delete_all
			end
			true
	end

		# def sendmail
		# 	@test_assessment_name = Assessment.find_by_id(self.assessment_id)
		# 	@test_user_name = User.find_by_id(self.user_id)
		# 	@user_name = @test_user_name.name
			
		
			
		# 	UserMailer.applicant_response_mail(@test_assessment_name, @test_user_name, @test_score).deliver_now
		# end
		
		
		
		#send mail with score and mail id of user
		

		# change password of user

		




		

end

app/models/assessment.rb
class Assessment < ActiveRecord::Base
	has_many :responses
	has_many :applicant_responses
	belongs_to :users
	has_many :questions, :dependent => :destroy
	has_many :test_scores
	accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

end

app/models/homepage.rb
class Homepage < ActiveRecord::Base
end

app/models/job_applicant.rb
class JobApplicant < ActiveRecord::Base
	mount_uploader :attachment, ResumeUploader
	validates :name, presence: true
	validates :emailid, presence: true
	validates_format_of :emailid, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
	
end

app/models/jobposting.rb
class Jobposting < ActiveRecord::Base
	validates :Job_Title, presence: true
	
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :assessment
	has_many :responses
	has_many :answers, :dependent => :destroy
	has_one :response
	accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/models/response.rb
class Response < ActiveRecord::Base
	belongs_to :user
	belongs_to :question
	belongs_to :answer
	belongs_to :assessment

	





	
end

app/models/shortlist.rb
class Shortlist < ActiveRecord::Base
	has_one :user
	


	accepts_nested_attributes_for :user
end

app/models/test_score.rb
class TestScore < ActiveRecord::Base
	belongs_to :assessment
	belongs_to :user
	
	
end

app/models/user.rb
class User < ActiveRecord::Base
	
	has_many :assessments
	belongs_to :shortlist
	has_many :responses
	has_many :test_scores
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,  :confirmable,
           :trackable, :validatable, :timeoutable



      
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
 module ApplicationHelper
  
end
  

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/shortlists_helper.rb
module ShortlistsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	
end

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge, chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="shortcut icon" href="/assets/icon.png">
    <title>


    <%= content_for?(:title) ? yield(:title) : "LIBSERV | HR Outsourcing, HRMS Solutions" %></title>
    

    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>

  <style type = "text/css">
    .navbar-inner
      {
        min-height: 0px;
      } 



    .navbar-brand,.navbar-nav >li> a 
      {
        line-height: 40px;
        height: 80px;
        padding-top: 50;
        
      }
     .panel, .panel-default
      {
        margin-left: 25px;
        margin-right: 25px;
      }
    .nav-pills
      {
        margin-left: 20px;

      }
    
    .nav, .nav-pills > li > a {
      color: #2952CC;
      font-size: 12pt;
      margin-left: 15px;
    }
    .footerdiv > a {
      color: black;
    }
    .footerdiv > a:hover {
      background-color: white;
    }
    .panel-body > .linkbar {
      vertical-align: top;
      ;
      
      


    }
    .panel-body > .linkbar1 {
      vertical-align: top;
      
      

      


    }
     .panel-body > .linkbar2 {
      vertical-align: top;
      
      text-align: right;
      


    }
    
   





  </style>
  <body>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href=<%=homepage_index_path%>><img src ="/assets/logo1-default.png" height = "50px"></a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">

          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Sign In", new_admin_session_path %></li>
              <li><%= link_to "WorkPro"  %></li>
          </ul>
        </div>
      </div>
    </div>
    <div class = "navbar-collapse collapse navbar-responsive-collapse">


    
      <ul class="nav nav-pills navbar-nav">
        
        <li><a href = <%= homepage_hr_products_path %>>Products</a>
         
        </li>
        <li><a href = <%=homepage_services_path%>>Services</a>
          
        </li>
        <li><a href = <%=homepage_about_us_path%>>About Us</a>
          
        </li>
        <li><a href = <%=homepage_careers_path%>>Careers</a></li>
      </ul>

    </div>

    <!---<div class="col-md-10 content">-->
    </br>
            <div class="panel panel-default">
                
                
        
          
<div class="panel-body">
                    <%= yield %></div><br><br>
                
            </div>
    <!--</div>-->

      <footer>
      
      
        <table width = "100%">
  <tr>
    <td align = "center">
      <a href = "https://twitter.com/libserv1" target="_blank"><img src = "/assets/twitter.png"></img></a>
      <a href = "https://www.linkedin.com/company/libserv" target="_blank"><img src = "/assets/linkedblog.png"></img></a>
      <a href = "https://libservblog.wordpress.com/" target="_blank"><img src = "/assets/linked.png"></img></a>
      <a href = "mailto:info@libserv.co"><img src = "/assets/mailus.jpg" alt = "send mail to us"></img></a><br><br>
      <font color = "#2952CC">Copyright © 2014 LIBSERV India Pvt. Ltd</font><br>
      <div class = "footerdiv">
      <a href = <%=homepage_careers_path %>>Careers</a> |
      <a href = "mailto:info@libserv.co">E-Mail</a> |
      <a href = "https://www.google.co.in/maps/place/Personnel+Search+Services+Private+Limited/@19.016795,72.828664,17z/data=!4m7!1m4!3m3!1s0x3be7cec0b1fd2b8f:0xf6d325a1642819fd!2sPersonnel+Search+Services+Private+Limited!3b1!3m1!1s0x3be7cec0b1fd2b8f:0xf6d325a1642819fd?hl=en" target="_blank">Contact</a> |
      <a href = <%=homepage_about_us_path%>>About Us</a>
      </div>
    </td>
  </tr>
</table><br>
      </footer>

     <!-- /container -->

  
  
</body>
</html>